### ISSUE TITLE
$_ POST

### ISSUE THREAD

**Issue by antonioortegajr** [dexlinx/SingleFormLead-Search#3]
In singleformresponse.php on line 68 there is a $data equaling an array. In the array $_POST is used, but htmlspecialchars() is not used to help prevent SQL injection.

**Comment by antonioortegajr** [comment]
actually this seems to happen more often than just the $data array.

**Comment by dexlinx** [comment]
Located a function to sanitize the $_POST var and updated code to use it. Now, all calls are pointing to the sanitized array
